name: Build WSA

on:
  workflow_dispatch:
    inputs:
      buildArch:
        description: "选择构建架构"
        required: true
        type: choice
        options:
          - X64
          - ARM64
      wsaVersion:
        description: "选择WSA版本"
        required: true
        type: choice
        options:
          - insider-fast
          - insider-slow
          - release
      magiskVersion:
        description: "选择Magisk版本"
        required: true
        type: choice
        options:
          - stable
          - beta
          - canary

jobs:
  build-wsa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 升级到v4版本

      - name: Set up QEMU
        uses: ./.github/actions/setup-qemu

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build WSA image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ secrets.DOCKER_REPO }}:${{ github.sha }}
          build-args: |
            ARCH=${{ inputs.buildArch }}
            WSA_CHANNEL=${{ inputs.wsaVersion }}
            MAGISK_CHANNEL=${{ inputs.magiskVersion }}
          push: true

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4  # 关键升级点
        with:
          name: wsa-${{ inputs.buildArch }}-${{ inputs.wsaVersion }}
          path: ./build/*.apk
          retention-days: 7

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
